[['trace', 0, 0, 1, 0], ['self', 0, 1, 1, 1]]
['code604', 'code603']
error: 0.0000327107824313888, n: 11, d: 3

